version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./media:/app/media
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - payload
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
