version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hett-cms:${TAG:-latest}
    container_name: hett-cms
    restart: unless-stopped
    ports:
      - "3007:3000"
    env_file:
      - stack.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URI=${DATABASE_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_EMAIL_HOST=${NEXT_PUBLIC_EMAIL_HOST}
      - NEXT_PUBLIC_EMAIL_PORT=${NEXT_PUBLIC_EMAIL_PORT}
      - NEXT_PUBLIC_EMAIL_USER=${NEXT_PUBLIC_EMAIL_USER}
      - NEXT_PUBLIC_EMAIL_PASS=${NEXT_PUBLIC_EMAIL_PASS}
      - NEXT_PUBLIC_EMAIL_FROM=${NEXT_PUBLIC_EMAIL_FROM}
      - NEXT_PUBLIC_EMAIL_TO=${NEXT_PUBLIC_EMAIL_TO}
    volumes:
      - ./public:/app/public
      - hett_media_data:/app/media
      - hett_uploads_data:/app/.next/server/chunks/uploads
    networks:
      - app-network
    labels:
      - "com.docker.stack.namespace=hett"
      - "com.hett.service.name=cms"
      - "com.hett.service.description=Hett CMS Backend"

volumes:
  hett_media_data:
    name: hett_media_data
    external: false
  hett_uploads_data:
    name: hett_uploads_data
    external: false

networks:
  app-network:
    driver: bridge 