version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8081:8081'
    env_file:
      - .env
    volumes:
      - ./public/media:/app/public/media
      - ./public/uploads:/app/public/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
